### ISSUE TITLE
Reduce the size/remove Application Builder logo

### ISSUE THREAD

**Issue by rpeach-sag** [SoftwareAG/cumulocity-app-builder#2]
The Application Builder logo is very large and appears every time you load an application.

Ideally we would show the logo for the specific application you are opening - this may not be possible because we can't get that info until the user is logged in.

Reducing the size or making it less "in your face" might help

**Comment by rpeach-sag** [comment]
One suggestion I've had is to just use the standard Cumulocity logo - with a global presales logo

**Comment by mstoffel-sag** [comment]
Please give that a higher prio. Some customers would like to use Appbuilder and need to put their own logo there.

**Comment by CarlesZ** [comment]
Agree, after the runtime widget functionality, customers are looking at  AppBuilder as an accelerator to their C8Y apps, so including a logo or just an free-to-choose image will be very beneficial.

**Comment by DarpanLalani** [comment]
Technically not feasible to change logo via configuration or settings. Since this is required to load before loading application.
If you would like to change logo, you can do at compile time by following below steps:
1. Clone the app builder repository
2.  Navigate to /ui-assets/img
3. Change  logo (keep the same file name or you can also update relevant styles in /ui-assets/index.less file)
4. Follow the "build Instructions" in ReadMe document
