### ISSUE TITLE
Widgets upload  gets stuck

### ISSUE THREAD

**Issue by gfavalli** [SoftwareAG/cumulocity-app-builder#51]
While opening application builder, it takes ages to upload opensource widgets and gets stuck at widget 4. It requires to refresh the page multiple times to get the total number of widgets loaded (30). 

Some people experiencing the error get a bad gw error

![badgw](https://user-images.githubusercontent.com/102232281/159709200-7d48aba6-ad10-4b26-89c5-cff672e53899.png)
![image](https://user-images.githubusercontent.com/102232281/159710455-5da19c28-484e-4266-aca7-83cf6431806a.png)

**Comment by CaribouJohn** [comment]
You got a 502 from trend miner widget - that indicates it is having issues connecting to the required connection. Look at the set up there. The fact that "trying it several times" worked eventually indicates infrastructure issues rather than an issue with app-builder. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
